name: Rebuild and Deploy on LMS or Frappe Update

on:
  repository_dispatch:
    types: [app_update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: olgagaga/lms-app
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

    steps:
    - name: Checkout frappe_docker
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        export APPS_JSON_BASE64=$(base64 -w 0 apps.json)
        docker build \
          --build-arg APPS_JSON_BASE64=$APPS_JSON_BASE64 \
          -f images/custom/Containerfile \
          -t $IMAGE_NAME:latest .

    - name: Push to Docker Hub
      run: docker push $IMAGE_NAME:latest

    - name: SSH to VPS and redeploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.VPS_HOST }}
        username: ${{ env.VPS_USER }}
        key: ${{ env.VPS_SSH_KEY }}
        script: |
          docker pull $IMAGE_NAME:latest
          python3 easy-install.py upgrade \
            --project learning_prod_setup \
            --image $IMAGE_NAME \
            --version latest \
            --app lms
